name: pontodofrango
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  curved_navigation_bar: ^1.0.6
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  path: ^1.9.0
  share_plus: ^10.0.2
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
