name: pontodofrango
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  archive: ^4.0.2
  curved_navigation_bar: ^1.0.6
  file_picker: ^8.3.1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  flutter_svg: ^2.0.10+1
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  http: ^1.3.0
  intl: ^0.19.0
  logger: ^2.5.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.2
  share_plus: ^10.0.2
  shared_preferences: ^2.5.1
  sqflite: ^2.3.3+1
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/icon.png
